import openai
import os
import dotenv

def add_resource(history, resource):
    conv = parse_conv(history, resource)

    dotenv.load_dotenv()
    openai.api_key = os.getenv("OPENAI_API_KEY")

    prompt = "Given the following conversation, I am to decide if it is appropriate to send the User " + \
            " a resource. A resource can be one of the following: \n" + \
            "1. A Youtube video \n" + \
            "2. A link to a website \n " + \
            "3. An excercise generated by an AI \n" + \
            "If I think it is appropriate, I will send the number of the resource I think is appropriate (For example \"1\" or \"2\").\n" + \
            "If I think it is not appropriate, I will send send \"0\". \n" + \
            "The conversation is as follows: \n"
    prompt += conv

    response = openai.Completion.create(
        model="gpt-3.5-turbo",
        prompt=prompt
    )
    
    print(response)

    return "test"

def parse_conv(history, resource):
    conv = ""
    for message in history:
        if message['role'] == 'system':
            conv += "System: " + message['content'] + "\n"
        elif message['role'] == 'user':
            conv += "User: " + message['content'] + "\n"
    conv += "System: " + resource + "\n"
    return conv